# Generated by Django 4.0.5 on 2022-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pic',
            field=models.FileField(default='media\\default_doc.png', upload_to='media\\images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
