# Generated by Django 4.0.5 on 2022-06-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doctor_pic_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pic',
            field=models.FileField(default='media\\default_pic.png', upload_to='media\\images'),
        ),
    ]
