# Generated by Django 4.0.5 on 2022-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pic',
            field=models.FileField(default='media/ddd.png', upload_to='media/images'),
        ),
    ]
