# Generated by Django 4.0.5 on 2022-07-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_patient_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='patient_id',
        ),
    ]
